"""One-off Monte Carlo prediction simulation for a user-specified 3-asset
portfolio (not part of the committee's own daily-picks system) — requested
directly, not generated by the committee's agents.

Uses ONLY real historical daily prices (yfinance) — no fabricated returns
or invented numbers. Method: joint bootstrap resampling of real historical
daily returns, drawing the *same* historical trading day's return for all
three assets together (so real historical co-movement between them is
preserved, not erased the way independently resampling each asset would),
repeated many times to build a distribution of possible outcomes over the
horizon — a distribution, not a single point guess.

Limitation stated plainly: NBIS and CRWV are recent IPOs with limited
real trading history, so the common-history sample pool this bootstraps
from is bounded by whichever of the three has the shortest history
(almost certainly CRWV) — a real constraint on how much this can say,
not smoothed over.

Meant to be run once via a temporary workflow_dispatch and then removed;
not a permanent part of this repo's committee pipeline.
"""
from __future__ import annotations

import json
import random

import yfinance as yf

WEIGHTS = {"SMH": 0.50, "NBIS": 0.30, "CRWV": 0.20}
HORIZON_TRADING_DAYS = 60  # ~3 months, matching this project's own hold horizon
N_TRIALS = 20000
PERIOD = "max"  # take all real history available for each symbol


def fetch_returns(symbol: str) -> tuple[list[str], list[float], float]:
    history = yf.Ticker(symbol).history(period=PERIOD, interval="1d")
    closes = history["Close"].tolist()
    dates = [ts.date().isoformat() for ts in history.index]
    returns = [closes[i] / closes[i - 1] - 1 for i in range(1, len(closes))]
    return dates[1:], returns, closes[-1]


def main() -> None:
    per_symbol: dict[str, dict] = {}
    for symbol in WEIGHTS:
        dates, returns, last_price = fetch_returns(symbol)
        per_symbol[symbol] = {"dates": dates, "returns": returns, "last_price": last_price}
        print(f"{symbol}: {len(returns)} real daily returns available (full history), last close ${last_price:.2f}")

    common_dates = set(per_symbol[next(iter(WEIGHTS))]["dates"])
    for s in WEIGHTS:
        common_dates &= set(per_symbol[s]["dates"])
    common_dates = sorted(common_dates)
    print(f"Common real trading history across all three: {len(common_dates)} days")
    if len(common_dates) < 60:
        print("WARNING: fewer than 60 common days of real overlapping history -- results below are low-confidence.")

    by_date = {s: dict(zip(per_symbol[s]["dates"], per_symbol[s]["returns"])) for s in WEIGHTS}

    rng = random.Random(7)
    portfolio_outcomes = []
    for _ in range(N_TRIALS):
        sampled_days = [rng.choice(common_dates) for _ in range(HORIZON_TRADING_DAYS)]
        cumulative = {s: 1.0 for s in WEIGHTS}
        for day in sampled_days:
            for s in WEIGHTS:
                cumulative[s] *= 1 + by_date[s][day]
        portfolio_return = sum(WEIGHTS[s] * (cumulative[s] - 1) for s in WEIGHTS)
        portfolio_outcomes.append(portfolio_return)

    portfolio_outcomes.sort()
    n = len(portfolio_outcomes)

    def pct(p: float) -> float:
        return portfolio_outcomes[min(n - 1, int(p * n))]

    result = {
        "weights": WEIGHTS,
        "n_trials": N_TRIALS,
        "horizon_trading_days": HORIZON_TRADING_DAYS,
        "common_history_days": len(common_dates),
        "per_symbol_history_days": {s: len(per_symbol[s]["returns"]) for s in WEIGHTS},
        "per_symbol_last_price": {s: round(per_symbol[s]["last_price"], 2) for s in WEIGHTS},
        "mean_return_pct": round(sum(portfolio_outcomes) / n * 100, 2),
        "median_return_pct": round(pct(0.50) * 100, 2),
        "p10_pct": round(pct(0.10) * 100, 2),
        "p25_pct": round(pct(0.25) * 100, 2),
        "p75_pct": round(pct(0.75) * 100, 2),
        "p90_pct": round(pct(0.90) * 100, 2),
        "prob_loss_pct": round(sum(1 for r in portfolio_outcomes if r < 0) / n * 100, 1),
        "worst_pct": round(portfolio_outcomes[0] * 100, 2),
        "best_pct": round(portfolio_outcomes[-1] * 100, 2),
    }
    print("RESULT_JSON_START")
    print(json.dumps(result, indent=2))
    print("RESULT_JSON_END")


if __name__ == "__main__":
    main()
